name: Deploy FastAPI to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image 
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push image to Azure Container Registry
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/aiforgood:latest .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/aiforgood:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: aiforgood
        images: ${{ secrets.ACR_LOGIN_SERVER }}/aiforgood:latest